#[warn(unused_must_use)]
mod guess;
mod basic;
mod owner;
mod strukt;
mod enumer;
mod matcher;
mod collections;
mod hashmap;
mod errors;
mod generic;
mod traits;
mod lifetime;
mod iter;
mod pointer;
mod refcell;
mod weak;
mod threads;
mod channels;
mod mutes;
mod pattern;
mod unsafety;
mod functions;
mod macros;
mod read;
mod borrow;
mod smart_pointer;
mod cow;
mod mem_leak;
mod intrin;
mod variant;
mod ch3;
mod mutexs;
mod barrier;
mod condvar;
mod head_first_rust;
mod overflow;

// use rust_playground::eat_at_restaurant;
// use crate::guess::guessing::guess;
// use crate::basic::variable_run;
// use crate::owner::owner_run;
// use crate::strukt::struct_run;
// use crate::enumer::enumer_run;
// use crate::matcher::match_run;
// use crate::collections::collections_run;
// use collections::collections_run;
// use hashmap::hashmap_run;
// use errors::errors_run;
// use generic::generic_run;
// use traits::trais_run;
// use lifetime::lifetime_run;
// use iter::iter_run;
// use pointer::pointer_run;
// use weak::weak_run;
// use threads::threads_run;
// use channels::channels_run;
// use mutes::mutes_run;
// use pattern::pattern_run;
// use unsafety::unsafety_run;
// use functions::functions_run;
// use macros::macros_run;
// use read::read_run;
// use borrow::borrow_run;
// use smart_pointer::smart_pointer_run;
// use cow::cow_run;
// use mem_leak::mem_leak_run;
// use intrin::intrin_run;
// use variant::variant_run;
// use ch3::ch3_run;
// use mutexs::mutexs_run;
// use barrier::barrier_run;
// use condvar::condvar_run;

fn main() {
    // println!("Hello, World!");
    // guess();
    // variable_run();
    // owner_run();
    // struct_run();
    // match_run();
    // eat_at_restaurant();
    // collections_run();
    // hashmap_run();
    // errors_run();
    // generic_run();
    // trais_run();
    // lifetime_run();
    // iter_run();
    // pointer_run();
    // refcell_run();
    // weak_run();
    // threads_run();
    // channels_run();
    // mutes_run();
    // pattern_run();
    // unsafety_run();
    // functions_run();
    // macros_run();
    // read_run();
    // borrow_run();
    // smart_pointer_run();
    // cow_run();
    // mem_leak_run();
    // intrin_run();
    // variant_run();
    // ch3_run();
    // mutexs_run();
    // barrier_run();
    // condvar_run();
    // chapter1::chapter1_run();
    // head_first_rust::chapter3::chapter3_run();
    // head_first_rust::chapter4::chapter4_run();
    // head_first_rust::chapter5::chapter5_run();
    // head_first_rust::chapter6::chapter6_run();
    // head_first_rust::chapter8::chapter8_run();
    // head_first_rust::chapter9::chapter9_run();
    // head_first_rust::chapter12::chapter12_run();
    // head_first_rust::chapter13::chapter13_run();
    // head_first_rust::chapter18::chapter18_run();
    // overflow::overflow_run();
    head_first_rust::chapter26::chapter26_run();
}